#---------------------------
# Hexo Theme Solitude
# Author: 王卓Sco、亦封
# Github: https://github.com/DuoSco/Hexo-theme-solitude
#
# 配置指南: https://docs.wzsco.top/
# 你可以从指南中获得更详细的说明
#
# Guide: https://docs.wzsco.top/
# You can get more detailed help from the guide
#---------------------------

# 站点设置
site:
  # 顶部导航栏logo区域
  name:
    # 显示类型 （i_class/text/img）
    class: text
    # 具体内容 例如：scoicon sco-logo / 王卓Sco / https://p.sondy.top/logo.png
    custom: Solitude
  # 网页icon
  siteIcon: https://bu.dusays.com/2023/11/08/654af68b25bb8.jpg
  # 页脚的Logo、加载动画默认的logo
  icon: https://bu.dusays.com/2023/11/08/654af68b25bb8.jpg
  # ICP 例如：湘ICP备2023015327号
  icp:
  # ICP链接 例如：http://www.beian.miit.gov.cn/
  icp_url:

# 导航栏
nav:
  #导航栏左侧
  left:
    # 是否开启左侧导航栏
    enable: false
    # 导航栏显示的内容
    menu:
    # 显示分类名
#      项目:
#        # 显示子类
#        Solitude:
#          # 显示的图标
#          icon: https://bu.dusays.com/2023/11/08/654af68b25bb8.jpg
#          # 点击的跳转链接
#          url: https://github.com/DuoSco/Hexo-Theme-solitude
    # ...

  # 导航栏内容
  # tip：此部分内容是顶部导航栏中间菜单区域
  menu:
    # 显示的大分类名称
    文库:
      # 点击跳转链接
      # tip：如果没有子类就填跳转链接，例如：/archives，否则填false
      url: false
      # 子类数组
      child:
        # 子类名称
        文章列表:
          # 点击跳转链接
          url: /archives/
          # 子类名称左侧图标
          icon: sco-folder-fill
        全部分类:
          url: /categories/
          icon: sco-checkbox-multiple-blank-fill
        全部标签:
          url: /tags/
          icon: sco-price-tag-fill
#      友链:
#        url: false
#        child:
#          友情链接:
#            url: /links/
#            icon: sco-group-fill
#          宝藏博主:
#            url: javascript:travelling()
#            icon: sco-gift-fill
#      我的:
#        url: false
#        child:
#          装备:
#            url: /equipment/
#            icon: sco-laptop-line
#          工具箱:
#            url: /tlink/
#            icon: sco-tools-fill
#      关于:
#        url: false
#        child:
#          关于本站:
#            url: /about/
#            icon: sco-contacts-fill


  # 导航栏右侧快捷菜单
  # tip：只需填写true和false即可
  right:
    random: false        # 随机文章跳转
    console: false       #控制台
    # 从左至右
    custom:
#      - name: 开往 - 友链接力
#        url: https://www.travellings.cn/go.html
#        icon: sco-train-line
#        onclick:
#        id: travellings_button

# 首页顶部样式
# tip：此内容为首页顶部的内容
hometop:
  # 首页顶部瀑布技能点、右侧文章推荐、左侧下部分三大分类
  banner:
    # 是否开启显示，不要开启则顶部只会显示即刻mini（需配置）
    enable: false # 是否打开顶部banner
    # 左上角显示大文字
    # tip：可使用html标签
    title: 宁静致远<br>热爱生活
    # 左上角显示小文字
    url: Hexo-Theme-Solitude
    # 轮播icon
    icon:
  #      HTML:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/HTML.png
  #        color: '#e9572b'
  #      JS:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/JS.png
  #        color: '#f7cb4f'
  #      Kotlin:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/kotlin-logo.svg
  #        color: '#ffffff'
  #      Docker:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/docker.png
  #        color: '#57b6e6'
  #      Flutter:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/flutter.png
  #        color: '#ffffff'
  #      WebPack:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/webpack.png
  #        color: '#2e3a41'
  #      Git:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/git.png
  #        color: '#df5b40'
  #      VS:
  #        img: https://npm.elemecdn.com/wleelw-blog-abs@1.0.0/img/icon/vs-logo.svg
  #        color: '#ffffff'

  # 顶部三大分类
  categoryGroup:
    # 左侧
    G1:
      # 显示文字
      name: 必看精选
      # 显示图标
      icon: scoicon sco-star-smile-fill
      # 跳转链接
      url: /tags/精选/
    # 中间
    G2:
      name: 热门文章
      icon: scoicon sco-fire-fill
      url: /categories/热门/
    # 右侧
    G3:
      name: 实用教程
      icon: scoicon sco-book-mark-fill
      url: /tags/教程/

  # 右侧置顶列表（在文章的front matter中添加“recommend: true”）
  recommendList:
    # 左上角显示文字
    sup: 置顶
    # 左下角大字
    title: Solitude主题文档
    # 点击跳转链接
    url: https://docs.wzsco.top/
    # 显示背景图片
    img: /img/default.png
    # 阴影颜色
    color: '#ff0000'

# 侧边栏
aside:
  # 值：about（关于我）、power（爱发电）、newestPost（最新文章）、allInfo（网站信息）、flip（公众号二维码）、welcome（个性定位）、history（那年今日）
  # 在主页显示的侧边栏信息
  # tip：将需要显示的侧边栏模块按照以上的值所述填入
  home:
    # 固定的信息（滑动不不跟随）
    noSticky: "about"
    # 不固定的信息（滑动跟随）
    Sticky: "allInfo"
  # 在文章页显示的侧边栏信息
  post:
    noSticky: "about"
    Sticky: "newestPost"
  # 在页面中显示的侧边栏信息
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  # 侧边栏个人信息卡片
  card:
    # 头像信息
    author:
      # 头像
      img: https://bu.dusays.com/2023/11/08/654af68b25bb8.jpg
      # 表情图片链接
      # tip: 推荐尺寸 26x26
      sticker: https://bu.dusays.com/2023/12/30/659011053e246.png
    # 文案1
    # tip：可使用html标签
    content: 分享自己对编程的<b>热爱</b>，对美好生活的<b>向往</b>，对知识海洋<b>探索历程</b>。
    # 文案2
    # tip：可使用html标签
    content2: 相信你可以在这里找到对你有用的知识和教程。
    # 个人信息卡片底部的小图标，按照例子填写
    information:
  #      # 悬停显示文字
  #      Github:
  #        # 图标
  #        icon: scoicon sco-github-line
  #        # 跳转链接
  #        url: https://github.com/DuoSco/Hexo-Theme-slitude
  #      Bilibili:
  #        icon: scoicon sco-bilibili-line
  #        url: https://space.bilibili.com/1329819902
  # 公众号二维码
  flip:
    # 右下角头像
    favicon:
    # 正面
    face:
    # 鼠标悬停翻转图片
    backface:
    # 夜间模式下是否开启卡片背景颜色 true：使用背景颜色 / false：不使用背景颜色
    darkcolor: false
  # 个性定位
  welcome:
    enable: false
    #【选填】留空将默认显示为：来访者
    title:
    #【选填】留空将默认显示为：scoicon sco-map-pin-line
    icon:
    # 腾讯key
    key:
    # 经度
    # tip：一定要改！不要用作者的经纬度！查询办法见文档
    longitude: 112.8455033596802
    # 纬度
    Latitude: 26.430308353457896
  # 那年今日
  history:
    enable: false
    #【选填】留空将默认显示为：那年今日
    title:
    #【选填】留空将默认显示为：scoicon sco-calendar-line
    icon:
  # 页面目录
  toc:
    # 在文章页显示
    post: true
    # 在任意页显示
    page: false
    # 开启后不悬停目录有模糊效果
    vague: true

  # 侧边栏文章列表
  tags:
    # 是否显示标签
    enable: false
    # 显示标签数量，当高于标签总数时，显示全部标签按钮
    limit: 20
    # 高亮显示
    highlight: false
    # 高亮显示标签列表
    list:
      - 'Solitude-使用'

  # 侧边栏归档
  archive:
    # 是否显示
    enable: false
    # 显示类型
    type: 'month' # monthly: 按月 / yearly: 按年

  # 建站信息
  siteinfo:
    # 文章数
    postcount: true
    # 总字数
    wordcount: true
    # 访问量
    pv: true
    # 访客数
    uv: true
    # 最后更新日期
    updatetime: true
    # 建站时间
    runtimeenable: true
    # 格式：yyyy-MM-dd hh-mm-ss
    runtime: '2023-04-20 00:00:00'

# Footer Settings
# --------------------------------------
footer:
  # 底部上方一排图标
  information:
    left: # 左侧显示图标
#      Github:
#        icon: scoicon sco-bilibili-line
#        url: https://github.com/wleelw
#      Mail:
#        icon: scoicon sco-mail-line
#        url: mailto:wleelw@wzsco.top
    right: # 右侧显示图标
#      Bilibili:
#        icon: scoicon sco-bilibili-line
#        url: https://space.bilibili.com/1329819902
#      抖音:
#        icon: scoicon sco-douyin-fill
#        url: https://v.douyin.com/iJsLc8jt/
  # 底部导航栏
  group: # 从左至右
#    导航:
#      归档: /archives/
#      分类: /categories/
#      标签: /tags/
#    服务:
#      阿里云: https://aliyun.com/
#      51la统计: https://v6.51.la/
#      百度统计: https://tongji.baidu.com/
#    支持:
#      打赏记录: /about/
#    协议:
#      Cookies: /cookies/
#      用户协议: /privacy/
#      版权协议: /copyright/

  # 底部随机友链
  # tip：此处的友链是随机显示的，不是固定的
  randomlink: false
  # 隐私助手
  privacy: # /privacy/
  # 订阅链接
  rss: # /rss/
  # 版权
  license: # /license/

# 页面页默认设置
page:
  error: true  # 404页面
  tags: true # 标签页
  categories: true # 分类页
  default: # 默认值
    # 默认图片
    # tip：随机数组图片，每次生成的时候都会从中随机抽取一张
    cover:
      - /img/default.png # 默认图片

# 文章页默认设置
post:
  default:
    # 文章默认图片
    # tip：同page的default
    cover:
      - /img/default.png # 默认图片
    locate: 衡阳
    copyright:
      # 是否打开copyright
      enable: true
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
      # 是否使用移轴动画头像
      author:
        enable: false
        author_back: https://bu.dusays.com/2023/11/01/6541f6d4b2573.png # 底部头像背景
  # 顶部文章简介
  meta:
    date: false # 发布日期
    updated: false # 更新日期
    locate: false # 位置
    wordcount: false # 字数
    readtime: false # 访问
    pv: false # 浏览量
    comment: false # 评论数
  # 打赏
  award:
    # 开启后文章底部显示打赏按钮
    enable: false
    # 微信收款码
    wechat: https://bu.dusays.com/2023/11/07/6549e79364fa3.png
    # 支付宝收款码
    alipay: https://bu.dusays.com/2023/11/07/6549e79d02bd6.png
    # 打赏统计页面链接
    url: /about
  rss: # /atom.xml
  # 文章颜色获取
  covercolor: #文章cover取色
    enable: false # 是否开启
    mode: local #local：本地取色 / api：img2color取色（无存缓） / api_redis：img2color取色（有存缓）
    api: https://img2color.meuicat.com/api?img=
    time: 43200000 # api取色间隔（毫秒），默认为12小时

# 关于界面
about: false

# 即刻说说界面
# 前置要求：需配置即刻说说页面
# 开启后将显示即刻页面
says:
  enable: false
  # 主页的即刻轮播条
  home_mini: false
  # 1：张洪heo样式 / 2：Leonus样式
  style: 1

# -------------------------
# 音乐相关配置
# meting-api
meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" #自定义api
# 音乐播放器界面
music:
  enable: false
  id: 1994908354
  # 播放列表的服务商。netease：网易云 / tencent：腾讯 / kugou：酷狗 / xiami：小米 / baidu：百度
  server: netease
  # 播放列表的类型。song：单曲 / playlist：歌单 / album：专辑 / artist：歌手
  type: playlist
  # 初始音量。0.8 = 80%，范围 0 到 1
  volume: 0.8
  # 是否开启互斥模式，即同时只能有一个播放器播放
  mutex: true

# 音乐胶囊
capsule:
  enable: false
  id: 8407304077 # 歌单id
  server: netease # 播放列表的服务商。netease：网易云 / tencent：腾讯 / kugou：酷狗 / xiami：小米 / baidu：百度
  type: playlist # 播放列表的类型。song：单曲 / playlist：歌单 / album：专辑 / artist：歌手

# -------------------------
# 404 页面
errorpage:
  # 图片
  img: https://npm.elemecdn.com/wzheo-absolute@1.0.3/image/source/404.png
  # 文字
  text: =awa= 页面走丢了
  # 推荐文章列表
  recommendList: true

# 懒加载
lazyload:
  # 是否开启
  enable: false
  # 加载中显示图片
  placeholder: /img/loading.gif
  # 加载失败显示图片
  errorimg: /img/error_load.png

# 图片灯箱
lightbox: false

#代码高亮增强
hightlight:
  enable: false
  # 代码块行高限制
  hightlimit: 200
  copy: true # 是否开启复制按钮
  expand: false # 是否默认展开
  # 代码块样式
  theme: default # default: 默认 / mac
  color: default # default: 默认  / vscode / solarized-dark / solarized-light / dracula / monokai

# 加载动画
loading:
  # 全局加载动画
  fullpage: false
  # 顶部加载胶囊
  pace: true

# 用于自定义的主题颜色
# 注意：颜色值必须使用引号，如“#000”，否则可能会导致错误！
# --------------------------------------
theme_color:
  dark: "#ffc848" # 暗色模式
  dark_op: '#f2b94b23' # 暗色模式透明
  dark_op_deep: '#f2b94bdd' # 暗色模式透明深色
  dark_none: '#f2b94b00' # 暗色模式透明无色
  light: "#425AEF" # 亮色模式
  light_op: '#4259ef23' # 亮色模式透明
  light_op_deep: '#4259efdd' # 亮色模式透明深色
  light_none: '#4259ef01' # 亮色模式透明无色

# 主题显示模式调整
# 主题支持三种模式：自动切换、暗色模式、亮色模式
# --------------------------------------
display_mode:
  type: auto # auto: 自动切换 / dark: 暗色模式 / light: 亮色模式
  dark_universe: true # 暗色模式背景星空

# --------------------------------------
# 第三方设置
# 字数统计
# tip：开启前需要安装字数统计插件
wordcount: false
# 访问统计
busuanzi: true

# 搜索
# tip：开启前需要安装搜索插件
search:
  enable: false
  # algolia, local
  type: algolia
  algolia_search:
    enable: false
    # hits:
    #   per_page: 6
  local_search:
    enable: false
    preload: false
    CDN:

# 文章页面AI
post-ai:
  enable: false # 是否开启
  # 右侧显示的模型名称
  modelName: GPT 4
  # key
  # 具体获取方法见文档
  key:
  # 自介
  talk: 我是王卓Sco开发的摘要生成助理ScoGPT，ScoGPT在静态部署时进行摘要的撰写，并且在访客访问时通过ScoCorrection转译后的文本摘要实现工具。我在这里只负责已经生成的摘要显示，你无法与我直接沟通，但我可以回答一些预设的问题。
  # 随机文章按钮
  randomPost: false
  # 举报链接，不填不显示
  report: https://blog.wzsco.top/about/
  # 底部提示
  tips: 此内容根据文章生成，并经过人工审核，仅用于文章内容的解释与总结

# 数学公式
katex:
  enable: false # 是否开启
  per_page: false # 是否在每页都加载
  copytex: false # 是否开启复制公式

# 评论
# --------------------------------------
comment:
  enable: false # 是否开启评论
  # waline, twikoo
  # tip：如果不需要评论系统，可以将enable设置为false
  type:
  commentBarrage: false # 热评开关
  newComment: false # 最新评论开关
  # 匿名评论前部分随机信息
  randomInfoStart:
    - '聪敏的'
    - '可爱的'
    - '美丽的'
  # 匿名评论后部分随机信息
  randomInfoEnd:
    - '白菜'
    - '小可爱'
    - '小仙女'
  # twikoo配置信息
  twikoo: # https://twikoo.js.org/
    envId: # url: https://twikoo.sondy.top/
    lang: 'zh-CN' # 语言
    accessToken:  # accessToken
  # waline配置信息
  waline: # https://waline.js.org/
    envId:  # url: https://waline.wzsco.top
    pageview: true # 是否开启页面访问量统计
    option: # waline配置项

# Open Graph
# --------------------------------------
# https://ogp.me/
# https://developers.facebook.com/docs/sharing/webmasters/
# tip: 开启后，将会在页面中插入 Open Graph 标签，用于社交分享。
opengraph:
  enable: false
  options:
#    twitter_card:
#    twitter_image:
#    twitter_id:
#    twitter_site:
#    google_plus:
#    fb_admins:
#    fb_app_id:

# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends:
  head: # 在head中插入
  # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
  body: # 在body中插入

# 文章底部推荐文章
related_post:
  enable: false
  # 推荐文章数量
  limit: 2
  # 根据创建日期（created）或是更新日期（updated）
  date_type: created

# rightside(右键菜单)
rightside:
  enable: false

# 站点验证
# 仅需要填写验证代码即可，譬如：codeva-KReTIJu5us
verify_site:
#  - name: google-site-verification
#    content: xxxxxx
#  - name: baidu-site-verification
#    content: xxxxxxx
# CSS 前缀
# 有些 CSS 并不是所有浏览器都支持，需要增加对应的前缀才会生效
# 开启 css_prefix 后，会自动为一些 CSS 增加前缀。（会增加 20%的体积）
# --------------------------------------
css_prefix: false

# PWA
# 图标信息非必选，填了就显示，不想添加的可以进行注释
# https://github.com/JLHwung/hexo-offline
pwa:
  enable: false # 是否开启
  manifest: /manifest.json # manifest.json 文件路径
  theme_color: '#ffffff' # 主题颜色
  mask_icon: https://fastly.jsdelivr.net/npm/solitude-source@1.0.0/img/pwa/180.png # 遮罩图标
  apple_touch_icon: https://fastly.jsdelivr.net/npm/solitude-source@1.0.0/img/pwa/180.png # 苹果触摸图标
  bookmark_icon: https://fastly.jsdelivr.net/npm/solitude-source@1.0.0/img/pwa/180.png # 书签图标
  favicon_32_32: https://fastly.jsdelivr.net/npm/solitude-source@1.0.0/img/pwa/32.png # 32x32图标
  favicon_16_16: https://fastly.jsdelivr.net/npm/solitude-source@1.0.0/img/pwa/16.png # 16x16图标

# CDN
# Don't modify the following settings unless you know how they work
# 非必要请不要修改
CDN:
  # The CDN provider of internal scripts (主题内 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom_cdn/custom
  # Dev version can only choose. ( dev版本只能为 local )
  internal: local
  # 自己搭建的cdn地址 默认路径：/source/$1
  custom_cdn:
  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  third_party: custom

  # Add version number to url, true or false
  version: true

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}

  option:
  # algolia_search:
  # instantsearch:
  # pjax:
  # twikoo:
  # waline_js:
  # waline_css:
  # sharejs:
  # sharejs_css:
  # katex:
  # katex_copytex:
  # lazyload:
  # aplayer_css:
  # aplayer_js:
  # meting_js:
  # pace_js:
  # lunr_js:
  # swiper_css:
  # swiper_js:
  # busuanzi_js:
  # snackbar_css:
  # snackbar_js: